apiVersion: apps/v1
kind: Deployment
metadata:
  name: gclocation-server
  labels:
    microservice: gclocation
spec:
  # modify replicas according to your case
  replicas: 1
  minReadySeconds: 2
  selector:
    matchLabels:
      microservice: gclocation
  template:
    metadata:
      labels:
        microservice: gclocation
    spec:
      containers:
      - name: gclocation-container
        image: gccloudregistry.azurecr.io/microservices/gclocation
        ports:
        - containerPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcmydata-server
  labels:
    microservice: gcmydata
spec:
  # modify replicas according to your case
  replicas: 1
  minReadySeconds: 2
  selector:
    matchLabels:
      microservice: gcmydata
  template:
    metadata:
      labels:
        microservice: gcmydata
    spec:
      containers:
      - name: gcmydata-container
        image: gccloudregistry.azurecr.io/microservices/gcmydata
        ports:
        - containerPort: 8097
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcgateway-server
  labels:
    microservice: gcgateway
spec:
  # modify replicas according to your case
  replicas: 1
  minReadySeconds: 2
  selector:
    matchLabels:
      microservice: gcgateway
  template:
    metadata:
      labels:
        microservice: gcgateway
    spec:
      containers:
      - name: gcgateway-container
        image: gccloudregistry.azurecr.io/microservices/gcgateway
        resources:
         limits:
          cpu: "100"
         requests:
          cpu: "100"
        env:
        - name: SERVER_URL
          value: "http://172.25.8.4:8080"
        ports:
        - containerPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcbatch-server
  labels:
    microservice: gcbatch
spec:
  # modify replicas according to your case
  replicas: 1
  minReadySeconds: 2
  selector:
    matchLabels:
      microservice: gcbatch
  template:
    metadata:
      labels:
        microservice: gcbatch
    spec:
      containers:
      - name: gcbatch-container
        image: gccloudregistry.azurecr.io/microservices/gcbatch
        ports:
        - containerPort: 8094
